// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumRWHD-9d_d1qJgOES0S1uqAZOqBo2kw',
    appId: '1:245443582356:android:6e900644bc8d47f9dad781',
    messagingSenderId: '245443582356',
    projectId: 'fir-cli-11b20',
    databaseURL: 'https://fir-cli-11b20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-cli-11b20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANFwPH0vGHNhCoce9-b8CApfRRoxXFYkI',
    appId: '1:245443582356:ios:3cb4b42aa3d4db02dad781',
    messagingSenderId: '245443582356',
    projectId: 'fir-cli-11b20',
    databaseURL: 'https://fir-cli-11b20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-cli-11b20.appspot.com',
    iosBundleId: 'com.example.firebaseCli',
  );
}
